# Generated by Django 4.1.7 on 2023-04-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communityuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
